
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywmqphwdzbmntfusemkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3bXFwaHdkemJtbnRmdXNlbWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxMjUzMDQsImV4cCI6MjA5MjcwMTMwNH0.ACLFQ5eaoqV2lS8uKlJlIB7uRpNj-ZrFTH9md5IXRDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
