
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwmdkgpnykpcyjofuxqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3bWRrZ3BueWtwY3lqb2Z1eHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDExMzMsImV4cCI6MjA2MTI3NzEzM30.fVxYKME_S69HMckEVHeY7awJcbM7RU80B0Zg3onCKoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
